/**
 * HR API
 * users host and get user info to db
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.api

import io.swagger.client.model.InlineResponse200
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object DefaultApi {

  /**
   * Allows users to get employee
   * 
   * Expected answers:
   *   code 200 : InlineResponse200 (OK)
   */
  def usersGet(): ApiRequest[InlineResponse200] =
    ApiRequest[InlineResponse200](ApiMethods.GET, "https://localhost", "/users", "application/json")
      .withSuccessResponse[InlineResponse200](200)
      

}

